import express from 'express';
import http from 'node:http';
import { Server } from 'socket.io';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import path from 'node:path';
import crypto from 'node:crypto';
import nodemailer from 'nodemailer';
import pg from 'pg';

const { Pool } = pg;
const app = express(), server = http.createServer(app), io = new Server(server);
const PORT = process.env.PORT || 3000;
const SECRET = process.env.DC_CHAT_SECRET;
const ADMIN_EMAIL = String(process.env.DC_CHAT_ADMIN_EMAIL || '').trim().toLowerCase();
if (process.env.NODE_ENV === 'production' && (!SECRET || SECRET.length < 32)) { console.error('Set DC_CHAT_SECRET to a random secret of at least 32 characters.'); process.exit(1); }
if (process.env.NODE_ENV === 'production' && !ADMIN_EMAIL) console.warn('DC_CHAT_ADMIN_EMAIL is not set.');
if (!process.env.DATABASE_URL) { console.error('DATABASE_URL is required. Set the Supabase PostgreSQL connection string in Render environment variables.'); process.exit(1); }
const JWT_SECRET = SECRET || 'local-development-only-change-before-deploy-123456';
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'disable' ? false : { rejectUnauthorized: false }, max: 5, idleTimeoutMillis: 30000, connectionTimeoutMillis: 10000 });
const resetCodes = new Map(), resetAttempts = new Map();
const smtpReady = !!(process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS && process.env.SMTP_FROM);
const mailer = smtpReady ? nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}) : null;
app.use(express.json({limit:'1mb'})); app.use(express.static(path.resolve('.')));
const cleanEmail = e => String(e||'').trim().toLowerCase();
const validGmail = e => /^[^\s@]+@gmail\.com$/.test(e);
const mapUser = r => r && ({uid:r.uid,email:r.email,name:r.name,role:r.role||'user',blocked:!!r.blocked,createdAt:new Date(r.created_at).getTime()});
const publicUser = u => ({uid:u.uid,email:u.email,name:u.name,role:u.role||'user',blocked:!!u.blocked,createdAt:u.createdAt});
const tokenFor = u => jwt.sign({uid:u.uid,email:u.email},JWT_SECRET,{expiresIn:'30d'});
async function userByEmail(email) { const q=await pool.query('select * from dc_chat_users where email=$1',[email]); return mapUser(q.rows[0]) ? {...mapUser(q.rows[0]),password:(q.rows[0].password_hash)} : null; }
async function userByUid(uid) { const q=await pool.query('select * from dc_chat_users where uid=$1',[uid]); return mapUser(q.rows[0]); }
async function auth(req,res,next) { try { const t=String(req.headers.authorization||'').replace(/^Bearer\s+/i,''); const c=jwt.verify(t,JWT_SECRET); const u=await userByEmail(c.email); if(!u||u.uid!==c.uid) return res.status(401).json({error:'Please log in again.'}); if(u.blocked) return res.status(403).json({error:'This account has been blocked by the app owner.'}); req.user=u; next(); } catch { res.status(401).json({error:'Please log in again.'}); } }
function adminOnly(req,res,next) { if(!req.user||req.user.role!=='admin'||req.user.email!==ADMIN_EMAIL) return res.status(403).json({error:'Owner admin access required.'}); next(); }
app.get('/health',async(_req,res)=>{ try { await pool.query('select 1'); res.json({ok:true,service:'DC Chat India',database:'connected',time:new Date().toISOString()}); } catch(e) { console.error('Health DB check failed:',e.message); res.status(503).json({ok:false,service:'DC Chat India',database:'disconnected'}); } });
app.get('/register',(_req,res)=>res.sendFile(path.resolve('register.html')));
app.get('/admin',(_req,res)=>res.sendFile(path.resolve('admin.html')));
app.post('/api/register',async(req,res)=>{ try {
 const email=cleanEmail(req.body.email),password=String(req.body.password||''),name=String(req.body.name||email.split('@')[0]).trim().slice(0,40);
 if(!validGmail(email)||password.length<8||!name) return res.status(400).json({error:'Use a Gmail address, display name, and password of at least 8 characters.'});
 const uid='DC'+crypto.randomBytes(4).toString('hex').toUpperCase(), hash=await bcrypt.hash(password,12),role=ADMIN_EMAIL&&email===ADMIN_EMAIL?'admin':'user';
 const q=await pool.query('insert into dc_chat_users(uid,email,name,password_hash,role,blocked,created_at) values($1,$2,$3,$4,$5,false,now()) returning *',[uid,email,name,hash,role]);
 const u=mapUser(q.rows[0]); res.status(201).json({token:tokenFor(u),user:publicUser(u)});
 } catch(e) { if(e.code==='23505') return res.status(409).json({error:'This Gmail already has a DC Chat account. Please log in.'}); console.error('Registration failed:',e.message); res.status(500).json({error:'Could not create account right now.'}); } });
app.post('/api/login',async(req,res)=>{ try { const email=cleanEmail(req.body.email),password=String(req.body.password||''),row=await pool.query('select * from dc_chat_users where email=$1',[email]),r=row.rows[0]; if(!validGmail(email)||!r||!(await bcrypt.compare(password,r.password_hash))) return res.status(401).json({error:'Gmail address or password is incorrect, or account is not registered.'}); const u=mapUser(r); if(u.blocked) return res.status(403).json({error:'This account has been blocked by the app owner.'}); res.json({token:tokenFor(u),user:publicUser(u)}); } catch(e) { console.error('Login failed:',e.message); res.status(500).json({error:'Login temporarily unavailable.'}); } });
app.get('/api/me',auth,(req,res)=>res.json(publicUser(req.user)));
app.get('/api/users/:uid',auth,async(req,res)=>{ try { const u=await userByUid(String(req.params.uid||'').toUpperCase()); if(!u||u.blocked) return res.status(404).json({error:'DC UID not found.'}); res.json({uid:u.uid,email:u.email,name:u.name}); } catch { res.status(500).json({error:'Could not look up user.'}); } });
app.get('/api/messages/:peer',auth,async(req,res)=>{ try { const peer=String(req.params.peer),me=req.user.uid; const q=await pool.query("select id::text, sender_uid as \"from\", recipient_uid as \"to\", body as text, (extract(epoch from created_at)*1000)::bigint as ts, (extract(epoch from created_at)*1000)::bigint as time, is_read as read, case when is_read then 'read' else 'sent' end as status from dc_chat_messages where (sender_uid=$1 and recipient_uid=$2) or (sender_uid=$2 and recipient_uid=$1) order by created_at desc limit 500",[me,peer]); res.json(q.rows.reverse()); } catch(e) { console.error('Messages fetch failed:',e.message); res.status(500).json({error:'Could not load messages.'}); } });
app.post('/api/messages',auth,async(req,res)=>{ try { const to=String(req.body.to||'').trim().toUpperCase(),body=String(req.body.text||'').slice(0,10000); if(!to||!body.trim()) return res.status(400).json({error:'Recipient and message are required.'}); const target=await userByUid(to); if(!target||target.blocked) return res.status(404).json({error:'Recipient DC UID not found.'}); const q=await pool.query('insert into dc_chat_messages(id,sender_uid,recipient_uid,body,created_at,is_read) values($1,$2,$3,$4,now(),false) returning id::text, sender_uid, recipient_uid, body, (extract(epoch from created_at)*1000)::bigint as ts, is_read',[crypto.randomUUID(),req.user.uid,target.uid,body]); const r=q.rows[0],m={id:r.id,from:r.sender_uid,to:r.recipient_uid,text:r.body,ts:Number(r.ts),time:Number(r.ts),read:r.is_read,status:'sent'}; io.to('user:'+target.uid).emit('message:new',m); res.status(201).json(m); } catch(e) { console.error('Message save failed:',e.message); res.status(500).json({error:'Could not send message.'}); } });
app.get('/api/admin/users',auth,adminOnly,async(_req,res)=>{ try { const q=await pool.query('select * from dc_chat_users order by created_at desc'); res.json(q.rows.map(mapUser)); } catch { res.status(500).json({error:'Could not load users.'}); } });
app.post('/api/admin/users/:uid/block',auth,adminOnly,async(req,res)=>{ try { const uid=String(req.params.uid||'').toUpperCase(),q=await pool.query('select * from dc_chat_users where uid=$1',[uid]),r=q.rows[0]; if(!r) return res.status(404).json({error:'User not found.'}); if(r.email===ADMIN_EMAIL) return res.status(400).json({error:'Owner account cannot be blocked.'}); const blocked=req.body.blocked!==false,updated=await pool.query('update dc_chat_users set blocked=$1 where uid=$2 returning *',[blocked,uid]); if(blocked) io.to('user:'+uid).emit('account:blocked'); res.json(mapUser(updated.rows[0])); } catch { res.status(500).json({error:'Could not update account.'}); } });
app.get('/api/admin/stats',auth,adminOnly,async(_req,res)=>{ try { const q=await pool.query("select (select count(*) from dc_chat_users) as users,(select count(*) from dc_chat_messages) as messages,(select count(*) from dc_chat_users where blocked) as blocked"); res.json({users:Number(q.rows[0].users),messages:Number(q.rows[0].messages),blocked:Number(q.rows[0].blocked)}); } catch { res.status(500).json({error:'Could not load stats.'}); } });
app.post('/api/forgot-password',async(req,res)=>{ const email=cleanEmail(req.body.email); if(!validGmail(email)) return res.status(400).json({error:'Enter the Gmail address used for your DC Chat account.'}); if(!mailer) return res.status(503).json({error:'Password recovery email is not configured yet. Please try again later.'}); const now=Date.now(),last=resetAttempts.get(email)||0; if(now-last<60000) return res.status(429).json({error:'Please wait one minute before requesting another code.'}); resetAttempts.set(email,now); try { const u=await userByEmail(email); if(!u) return res.json({ok:true,message:'If a DC Chat account exists for this Gmail, a verification code has been sent.'}); const code=String(crypto.randomInt(0,1000000)).padStart(6,'0'); resetCodes.set(email,{hash:crypto.createHash('sha256').update(code).digest('hex'),expires:now+600000,attempts:0}); await mailer.sendMail({from:process.env.SMTP_FROM,to:email,subject:'Your DC Chat password reset code',text:`Hello ${u.name}, your DC Chat reset code is ${code}. It expires in 10 minutes.`}); res.json({ok:true,message:'Verification code sent if this Gmail is registered. Check Inbox and Spam.'}); } catch(e) { resetCodes.delete(email); console.error('Reset email failed:',e.message); res.status(502).json({error:'Could not send the email right now.'}); } });
app.post('/api/reset-password',async(req,res)=>{ const email=cleanEmail(req.body.email),code=String(req.body.code||'').trim(),password=String(req.body.password||''); if(!validGmail(email)||!/^\d{6}$/.test(code)) return res.status(400).json({error:'Enter your Gmail and the 6-digit code.'}); if(password.length<8) return res.status(400).json({error:'New password must be at least 8 characters.'}); const e=resetCodes.get(email); let u; try { u=await userByEmail(email); } catch { return res.status(500).json({error:'Try again later.'}); } if(!e||!u||e.expires<Date.now()) { resetCodes.delete(email); return res.status(400).json({error:'Code expired or invalid. Request a new code.'}); } e.attempts++; const candidate=crypto.createHash('sha256').update(code).digest('hex'); if(e.attempts>5||!crypto.timingSafeEqual(Buffer.from(e.hash,'hex'),Buffer.from(candidate,'hex'))) { if(e.attempts>=5) resetCodes.delete(email); return res.status(400).json({error:'Code is incorrect or expired.'}); } try { await pool.query('update dc_chat_users set password_hash=$1 where email=$2',[await bcrypt.hash(password,12),email]); resetCodes.delete(email); res.json({ok:true,message:'Password updated. You can now log in with your new password.'}); } catch { res.status(500).json({error:'Could not update password.'}); } });
io.use(async(socket,next)=>{ try { const c=jwt.verify(socket.handshake.auth?.token,JWT_SECRET),u=await userByEmail(c.email); if(!u||u.uid!==c.uid||u.blocked) return next(new Error('Unauthorized')); socket.user=u; next(); } catch { next(new Error('Unauthorized')); } });
io.on('connection',socket=>{ socket.join('user:'+socket.user.uid); socket.emit('ready',{uid:socket.user.uid}); socket.on('typing',({to,typing}={})=>{ if(typeof to==='string') io.to('user:'+to).emit('typing',{from:socket.user.uid,typing:!!typing}); }); socket.on('read',async({id}={})=>{ try { const q=await pool.query('update dc_chat_messages set is_read=true where id=$1 and recipient_uid=$2 returning id::text,sender_uid',[id,socket.user.uid]); if(q.rowCount) io.to('user:'+q.rows[0].sender_uid).emit('message:read',{id:q.rows[0].id}); } catch(e) { console.error('Read receipt failed:',e.message); } }); });
app.get('/',(_req,res)=>res.sendFile(path.resolve('DC_Chat_Final_V20.html')));
server.listen(PORT,()=>console.log('DC Chat listening on port '+PORT));
